/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.tasktoo;
import java.io.File;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.DocumentBuilder;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;

public class App {
    public String getGreeting() {
        return "Hello Task two";
    }

    public static void main(String[] args) {
        try {
            File inputFile = new File("example.xml");
            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
            Document doc = dBuilder.parse(inputFile);
            doc.getDocumentElement().normalize();
            NodeList nList = doc.getElementsByTagName("book");
            for (int temp = 0; temp < nList.getLength(); temp++) {
                Node nNode = nList.item(temp);
                if (nNode.getNodeType() == Node.ELEMENT_NODE) {
                    System.out.println("Title : " + ((org.w3c.dom.Element) nNode).getElementsByTagName("title").item(0).getTextContent());
                    System.out.println("Author : " + ((org.w3c.dom.Element) nNode).getElementsByTagName("author").item(0).getTextContent());
                    System.out.println("Year : " + ((org.w3c.dom.Element) nNode).getElementsByTagName("year").item(0).getTextContent());
                    System.out.println("Price : " + ((org.w3c.dom.Element) nNode).getElementsByTagName("price").item(0).getTextContent());
                    System.out.println("-----------");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
